<?php
declare(strict_types=1);

function detect_lang(): string {
    // Default to English. The user can opt into Swedish via the flag in the
    // header (which sets a cookie); browser Accept-Language is no longer
    // consulted — too many Swedish-locale users want the English copy.
    if (!empty($_COOKIE['lang']) && in_array($_COOKIE['lang'], ['sv', 'en'], true)) {
        return $_COOKIE['lang'];
    }
    return 'en';
}

function set_lang(string $lang): void {
    $GLOBALS['LANG'] = $lang;
}

const CURRENCIES = ['sek', 'eur', 'usd'];

// Visitor-selected billing currency. Cookie-set via ?currency= in index.php,
// rendered in views/_lang_switch.php, and forwarded to Stripe Checkout so
// the session is denominated in the matching currency. Default SEK because
// Klarna recurring requires SEK or EUR and the primary market is Swedish.
function detect_currency(): string {
    if (!empty($_COOKIE['currency']) && in_array($_COOKIE['currency'], CURRENCIES, true)) {
        return $_COOKIE['currency'];
    }
    return 'sek';
}

function set_currency(string $cur): void {
    $GLOBALS['CURRENCY'] = $cur;
}

// Display strings for Pro plan prices per currency. Kept in PHP so the
// landing page pricing block can render server-side; the JS upgrade panel
// keeps its own copy in assets/js/app.js (PRICES) — update both if you
// change the amounts.
const PRICE_DISPLAY = [
    'sek' => ['monthly' => '49 kr', 'yearly' => '490 kr'],
    'eur' => ['monthly' => '€4,99', 'yearly' => '€49'   ],
    'usd' => ['monthly' => '$5',    'yearly' => '$50'   ],
];

function price_display(string $plan): string {
    $cur = $GLOBALS['CURRENCY'] ?? 'sek';
    return PRICE_DISPLAY[$cur][$plan] ?? '';
}

function t(string $key, string ...$args): string {
    $lang = $GLOBALS['LANG'] ?? 'en';
    static $strings = null;
    if ($strings === null) $strings = lang_strings();
    $s = $strings[$lang][$key] ?? $strings['en'][$key] ?? $key;
    return $args ? sprintf($s, ...$args) : $s;
}

function lang_strings(): array {
    return [
        'sv' => [
            // Nav
            'nav_signin'      => 'Logga in',
            'nav_dashboard'   => 'Dashboard',
            'nav_new_link'    => 'Ny länk',
            'nav_signout'     => 'Logga ut',
            // Landing
            'eyebrow'         => 'URL-förkortare · egenhostad',
            'hero_title'      => 'Gör en lång URL <em>kortare.</em>',
            'hero_lede'       => 'Klistra in en länk. Få en kort. Lägg till ett lösenord, ett utgångsdatum eller ett slug du kommer ihåg. Logga in för klickstatistik.',
            'btn_shorten'     => 'Förkorta',
            'anon_link_warning' => 'Länkar du skapar utan att vara inloggad raderas automatiskt efter 30 minuter.',
            'advanced_toggle' => 'Eget slug, utgångsdatum, lösenord',
            'label_slug'      => 'Eget slug',
            'label_expires'   => 'Utgår',
            'label_password'  => 'Lösenord',
            'placeholder_pw'  => 'Lösenord',
            'btn_copy'        => 'Kopiera',
            'btn_qr'          => 'QR',
            'btn_new'         => 'Nytt',
            'feat1_title'     => 'Egna slug',
            'feat1_body'      => 'Välj ditt eget slut. <code>/launch</code>, <code>/menu</code>, vad som passar.',
            'feat2_title'     => 'Utgångsdatum &amp; lösenord',
            'feat2_body'      => 'Tidsbegränsa en länk eller skydda den med lösenord — perfekt för engångsdelning.',
            'feat3_title'     => 'Klickstatistik',
            'feat3_body'      => 'Logga in så får varje länk daglig räkning, senaste klick och hänvisande sidor.',
            // Auth
            'signin_title'    => 'Logga in.',
            'register_title'  => 'Skapa ett konto.',
            'signin_sub'      => 'Välkommen tillbaka. Eller <a href="%s">skapa ett nytt konto</a>.',
            'register_sub'    => 'Spåra dina länkar och klickstatistik. Eller <a href="%s">logga in</a>.',
            'label_name'      => 'Namn',
            'label_email'     => 'E-post',
            'label_email_confirm' => 'Bekräfta e-post',
            'btn_signin'      => 'Logga in',
            'btn_register'    => 'Skapa konto',
            'aux_verify_link' => 'Har du redan en kod? Verifiera här.',
            'forgot_link'     => 'Glömt lösenord?',
            // Forgot / reset password
            'title_forgot'    => 'Glömt lösenord — Shortly',
            'title_reset'     => 'Välj nytt lösenord — Shortly',
            'forgot_title'    => 'Glömt lösenord.',
            'forgot_sub'      => 'Skriv in e-postadressen du registrerade dig med — om den finns hos oss skickar vi en länk för att välja ett nytt lösenord.',
            'btn_forgot'      => 'Skicka återställningslänk',
            'forgot_sent'     => 'Om e-posten finns hos oss har vi skickat en länk. Kolla inboxen (och spam).',
            'reset_title'     => 'Välj nytt lösenord.',
            'reset_sub'       => 'Skriv in ett nytt lösenord (minst 8 tecken).',
            'reset_done'      => 'Klart. Du kan nu logga in med ditt nya lösenord.',
            'reset_invalid'   => 'Länken är ogiltig eller har gått ut. Begär en ny återställningslänk.',
            'reset_used'      => 'Länken har redan använts. Begär en ny om du behöver återställa igen.',
            'btn_reset'       => 'Spara nytt lösenord',
            'btn_to_login'    => 'Till inloggning',
            'btn_to_forgot'   => 'Begär ny länk',
            'err_weak_password' => 'Lösenordet måste vara minst 8 tecken.',
            // Verification
            'verify_title'    => 'Bekräfta din e-post.',
            'verify_sub'      => 'Vi skickade en 6-siffrig kod till <strong>%s</strong>. Ange den nedan för att slutföra registreringen.',
            'verify_sub_blank'=> 'Ange e-postadressen och 6-siffrig kod du fick i mailet.',
            'label_code'      => 'Kod',
            'btn_verify'      => 'Verifiera',
            'verify_resend'   => 'Skicka en ny kod',
            'verify_resent'   => 'Ny kod skickad om e-posten finns registrerad.',
            'err_email_mismatch'   => 'E-postadresserna stämmer inte överens.',
            'err_all_fields'       => 'Alla fält måste fyllas i.',
            'err_name_long'        => 'Namnet får vara max 100 tecken.',
            'err_invalid_code'     => 'Fel kod.',
            'err_code_format'      => 'Koden ska vara 6 siffror.',
            'err_expired'          => 'Koden har gått ut. Registrera dig igen.',
            'err_too_many'         => 'För många försök. Registrera dig igen.',
            'title_verify'         => 'Bekräfta e-post — Shortly',
            // Bio
            'title_bio_editor'     => 'Bio-sida — Shortly',
            'bio_editor_title'     => 'Din bio-sida',
            'bio_editor_sub'       => 'Skapa en publik landningssida med dina utvalda länkar.',
            'bio_label_slug'       => 'Slug',
            'bio_label_title'      => 'Rubrik',
            'bio_label_theme'      => 'Tema',
            'bio_label_links'      => 'Länkar',
            'bio_add_link'         => 'Lägg till länk',
            'bio_save'             => 'Spara',
            'bio_delete'           => 'Ta bort sidan',
            'bio_delete_confirm'   => 'Säker på att du vill ta bort din bio-sida?',
            'bio_saved'            => 'Sparat.',
            'bio_view_link'        => 'Öppna offentlig sida',
            'bio_link_label'       => 'Etikett',
            'bio_link_url'         => 'URL',
            // Keys
            'title_keys'           => 'API-nycklar — Shortly',
            'keys_title'           => 'API-nycklar',
            'keys_sub'             => 'Skapa nycklar för programmatisk åtkomst. Free: 100 anrop/h. Pro: 1000 anrop/h.',
            'keys_create'          => 'Skapa ny nyckel',
            'keys_label_label'     => 'Etikett',
            'keys_revoke'          => 'Återkalla',
            'keys_revoke_confirm'  => 'Återkalla nyckeln? Skript som använder den slutar fungera.',
            'keys_show_once'       => 'Detta är enda gången nyckeln visas. Spara den nu.',
            'keys_copy'            => 'Kopiera',
            'keys_no_keys'         => 'Inga nycklar än.',
            'nav_bio'              => 'Bio',
            'nav_keys'             => 'API',
            // Billing (sv)
            'billing_curr_label'   => 'Valuta',
            // Landing pricing section (sv)
            'pricing_h'            => 'Välj plan',
            'pricing_sub'          => 'Börja gratis. Uppgradera när du behöver mer.',
            'pricing_most_value'   => 'Mest värde',
            'pricing_per_month'    => '/ månad',
            'pricing_per_year'     => '/ år',
            'pricing_free'         => 'Gratis',
            'tier_free'            => 'Free',
            'tier_pro_monthly'     => 'Pro · månad',
            'tier_pro_yearly'      => 'Pro · år',
            'tier_free_tag'        => 'För småfix och privatbruk.',
            'tier_pro_tag'         => 'För dig som delar länkar regelbundet.',
            'tier_free_f1'         => 'Korta länkar utan konto eller med',
            'tier_free_f2'         => 'Klickstatistik',
            'tier_free_f3'         => 'Automatiskt utgångsdatum',
            'tier_free_f4'         => '100 API-anrop/timme',
            'tier_pro_f1'          => 'Allt i Free',
            'tier_pro_f2'          => 'Lösenordsskydd',
            'tier_pro_f3'          => 'Anpassad utgång (eller ingen)',
            'tier_pro_f4'          => 'Redigerbara länkar',
            'tier_pro_f6'          => '1000 API-anrop/timme',
            'pricing_cta_free'     => 'Skapa konto',
            'pricing_cta_pro'      => 'Välj Pro',
            'pricing_cta_app'      => 'Till dashboard',
            'billing_upgrade_h'    => 'Uppgradera till Pro',
            'billing_upgrade_sub'  => 'Få avancerad statistik, redigerbara länkar, lösenordsskydd, anpassad utgång och mer.',
            'billing_yearly_save'  => 'Spara 17%',
            'billing_btn_monthly'  => 'Välj månadsplan',
            'billing_btn_yearly'   => 'Välj årsplan',
            'billing_pro_h'        => 'Du är Pro ✓',
            'billing_pro_plan'     => 'Plan',
            'billing_pro_renews'   => 'Förnyas',
            'billing_pro_cancels'  => 'Sägs upp vid periodens slut',
            'billing_pro_status'   => 'Status',
            'billing_manage'       => 'Hantera prenumeration',
            'billing_thanks'       => 'Tack — uppgraderingen är klar.',
            'billing_canceled'     => 'Uppgraderingen avbröts.',
            'err_invalid_plan'     => 'Ogiltig plan.',
            'err_no_subscription'  => 'Du har ingen aktiv prenumeration.',
            'err_billing_unavailable' => 'Betalning är inte tillgänglig just nu.',
            // Pro-gated features (sv)
            'err_password_pro'     => 'Lösenordsskydd kräver Pro.',
            'err_expiry_pro'       => 'Anpassat utgångsdatum kräver Pro.',
            'err_upgrade_required' => 'Den funktionen kräver Pro.',
            'edit_link'            => 'Redigera länk',
            'edit_save'            => 'Spara',
            'edit_cancel'          => 'Avbryt',
            'edit_clear_password'  => 'Ta bort lösenord',
            'edit_clear_expiry'    => 'Ta bort utgång',
            'edit_keep_password'   => 'Lämna oförändrat',
            'edit_new_password'    => 'Nytt lösenord',
            'edit_saved'           => 'Sparat.',
            'utm_title'            => 'UTM-byggare',
            'utm_sub'              => 'Lägg till spårningsparametrar på en URL.',
            'utm_field_url'        => 'Bas-URL',
            'utm_field_source'     => 'Källa (utm_source)',
            'utm_field_medium'     => 'Medium (utm_medium)',
            'utm_field_campaign'   => 'Kampanj (utm_campaign)',
            'utm_field_term'       => 'Sökord (utm_term, frivilligt)',
            'utm_field_content'    => 'Innehåll (utm_content, frivilligt)',
            'utm_result'           => 'Färdig URL',
            'utm_copy'             => 'Kopiera',
            'csv_export'           => 'Exportera klick (CSV)',
            'devices_title'        => 'Enheter',
            // Abuse report (sv)
            'title_report'         => 'Rapportera missbruk — Shortly',
            'report_title'         => 'Rapportera en kort länk',
            'report_sub'           => 'Misstänker du phishing, malware eller olagligt innehåll? Berätta så granskar vi.',
            'report_field_slug'    => 'Slug (delen efter /)',
            'report_field_reason'  => 'Anledning',
            'report_field_detail'  => 'Detaljer (valfritt)',
            'report_reason_phishing' => 'Phishing',
            'report_reason_malware'  => 'Malware',
            'report_reason_illegal'  => 'Olagligt innehåll',
            'report_reason_spam'     => 'Spam',
            'report_reason_other'    => 'Annat',
            'report_submit'        => 'Skicka rapport',
            'report_thanks'        => 'Tack — rapporten är registrerad. Vi granskar och tar ner länken om den bryter mot reglerna.',
            'report_suspended'     => 'Länken har redan avstängts.',
            'err_url_blocked'      => 'Den URL-domänen är blockerad eftersom den är känd för phishing/malware.',
            'err_url_blocked_threat' => 'URL:en flaggad som hot av Google Safe Browsing.',
            'err_url_ip_host'      => 'IP-adresser som värd är inte tillåtna — använd ett domännamn.',
            'err_url_internal_host' => 'Den värden ser intern ut (localhost / .local / .internal osv) — använd en publik domän.',
            'err_target_self'      => 'Du kan inte korta en länk som pekar tillbaka på den här tjänsten.',
            'err_target_too_freq'  => 'Den URL:en har korthats för många gånger nyligen — försök igen om en stund.',
            'err_captcha'          => 'Verifiering misslyckades. Ladda om sidan och försök igen.',
            'err_link_suspended'   => 'Länken har avstängts på grund av rapporter.',
            // Dashboard
            'dash_title'      => 'Dina länkar.',
            'dash_empty'      => 'Inga länkar än.',
            'dash_empty_sub'  => 'Skapa din första — <a href="%s" style="color:var(--accent);font-weight:500;">börja här</a>.',
            // Unlock
            'unlock_code'     => 'Lösenord krävs',
            'unlock_title'    => 'Den här länken är låst.',
            'unlock_sub'      => 'Ägaren skyddade den med ett lösenord. Ange det för att fortsätta.',
            'btn_unlock'      => 'Lås upp och fortsätt',
            // Footer
            'foot_tagline'    => 'Svensk webbutveckling med 30 års IT-bakgrund och AI som kraftmultiplikator.',
            'foot_svc_head'   => 'Tjänster',
            'foot_cmp_head'   => 'Företag',
            'foot_con_head'   => 'Kontakt',
            'foot_systems'    => 'Alla system online',
            'foot_ftax'       => 'Innehar F-skatt',
            'foot_report_link' => 'Rapportera missbruk',
            'foot_bis_member' => 'Stolt medlem av Based In Sweden',
            // Consent banner
            'consent_text'    => 'Vi loggar varje besök (IP, webbläsare, tid) för intern statistik — inga spårningscookies eller tredjepartsspårare. (Funktions­cookies för inloggning och språkval används endast när du själv använder de funktionerna.)',
            'consent_accept'  => 'Acceptera',
            'consent_decline' => 'Avböj',
            'consent_reset'   => 'Integritet',
            'consent_aria'    => 'Sekretess­meddelande',
            // Page titles
            'title_landing'   => 'Shortly — URL-förkortare',
            'title_signin'    => 'Logga in — Shortly',
            'title_register'  => 'Skapa konto — Shortly',
            'title_dashboard' => 'Dashboard — Shortly',
            'title_unlock'    => 'Lösenord krävs — Shortly',
        ],
        'en' => [
            // Nav
            'nav_signin'      => 'Sign in',
            'nav_dashboard'   => 'Dashboard',
            'nav_new_link'    => 'New link',
            'nav_signout'     => 'Sign out',
            // Landing
            'eyebrow'         => 'URL shortener · self-hosted',
            'hero_title'      => 'Make a long URL <em>shorter.</em>',
            'hero_lede'       => 'Drop a link. Get a short one. Add a password, an expiry, or a slug you\'ll remember. Sign in to keep the click stats.',
            'btn_shorten'     => 'Shorten',
            'anon_link_warning' => 'Links you create while signed out are deleted automatically after 30 minutes.',
            'advanced_toggle' => 'Custom slug, expiry, password',
            'label_slug'      => 'Custom slug',
            'label_expires'   => 'Expires',
            'label_password'  => 'Password',
            'placeholder_pw'  => 'Password',
            'btn_copy'        => 'Copy',
            'btn_qr'          => 'QR',
            'btn_new'         => 'New',
            'feat1_title'     => 'Custom slugs',
            'feat1_body'      => 'Pick your own short ending. <code>/launch</code>, <code>/menu</code>, whatever fits.',
            'feat2_title'     => 'Expiry &amp; passwords',
            'feat2_body'      => 'Time-bomb a link or hide it behind a password — useful for one-off shares.',
            'feat3_title'     => 'Click stats',
            'feat3_body'      => 'Sign in and every link gets daily counts, recent clicks, and referrers.',
            // Auth
            'signin_title'    => 'Sign in.',
            'register_title'  => 'Create an account.',
            'signin_sub'      => 'Welcome back. Or <a href="%s">create a new account</a>.',
            'register_sub'    => 'Track your links and click stats. Or <a href="%s">sign in</a>.',
            'label_name'      => 'Name',
            'label_email'     => 'Email',
            'label_email_confirm' => 'Confirm email',
            'btn_signin'      => 'Sign in',
            'btn_register'    => 'Create account',
            'aux_verify_link' => 'Already have a code? Verify here.',
            'forgot_link'     => 'Forgot password?',
            // Forgot / reset password
            'title_forgot'    => 'Forgot password — Shortly',
            'title_reset'     => 'Choose a new password — Shortly',
            'forgot_title'    => 'Forgot password.',
            'forgot_sub'      => 'Enter the email you signed up with — if we have it on file, we\'ll email you a link to choose a new password.',
            'btn_forgot'      => 'Send reset link',
            'forgot_sent'     => 'If we have that email, we\'ve sent you a link. Check your inbox (and spam).',
            'reset_title'     => 'Choose a new password.',
            'reset_sub'       => 'Pick a new password (at least 8 characters).',
            'reset_done'      => 'Done. You can now sign in with your new password.',
            'reset_invalid'   => 'This link is invalid or has expired. Please request a new reset link.',
            'reset_used'      => 'This link has already been used. Request a new one if you need to reset again.',
            'btn_reset'       => 'Save new password',
            'btn_to_login'    => 'Go to sign in',
            'btn_to_forgot'   => 'Request a new link',
            'err_weak_password' => 'Password must be at least 8 characters.',
            // Verification
            'verify_title'    => 'Confirm your email.',
            'verify_sub'      => 'We sent a 6-digit code to <strong>%s</strong>. Enter it below to finish registration.',
            'verify_sub_blank'=> 'Enter the email and 6-digit code you received.',
            'label_code'      => 'Code',
            'btn_verify'      => 'Verify',
            'verify_resend'   => 'Resend code',
            'verify_resent'   => 'A new code has been sent if the email is registered.',
            'err_email_mismatch'   => 'The email addresses don\'t match.',
            'err_all_fields'       => 'All fields are required.',
            'err_name_long'        => 'Name must be 100 characters or fewer.',
            'err_invalid_code'     => 'Wrong code.',
            'err_code_format'      => 'The code must be 6 digits.',
            'err_expired'          => 'The code has expired. Please register again.',
            'err_too_many'         => 'Too many attempts. Please register again.',
            'title_verify'         => 'Verify email — Shortly',
            // Bio
            'title_bio_editor'     => 'Bio page — Shortly',
            'bio_editor_title'     => 'Your bio page',
            'bio_editor_sub'       => 'Build a public landing page with your curated links.',
            'bio_label_slug'       => 'Slug',
            'bio_label_title'      => 'Title',
            'bio_label_theme'      => 'Theme',
            'bio_label_links'      => 'Links',
            'bio_add_link'         => 'Add link',
            'bio_save'             => 'Save',
            'bio_delete'           => 'Delete page',
            'bio_delete_confirm'   => 'Sure you want to delete your bio page?',
            'bio_saved'            => 'Saved.',
            'bio_view_link'        => 'Open public page',
            'bio_link_label'       => 'Label',
            'bio_link_url'         => 'URL',
            // Keys
            'title_keys'           => 'API keys — Shortly',
            'keys_title'           => 'API keys',
            'keys_sub'             => 'Create keys for programmatic access. Free: 100 calls/h. Pro: 1000 calls/h.',
            'keys_create'          => 'Create new key',
            'keys_label_label'     => 'Label',
            'keys_revoke'          => 'Revoke',
            'keys_revoke_confirm'  => 'Revoke this key? Scripts using it will stop working.',
            'keys_show_once'       => 'This is the only time this key is shown. Save it now.',
            'keys_copy'            => 'Copy',
            'keys_no_keys'         => 'No keys yet.',
            'nav_bio'              => 'Bio',
            'nav_keys'             => 'API',
            // Billing (en)
            'billing_curr_label'   => 'Currency',
            // Landing pricing section (en)
            'pricing_h'            => 'Choose your plan',
            'pricing_sub'          => 'Start free. Upgrade when you need more.',
            'pricing_most_value'   => 'Most value',
            'pricing_per_month'    => '/ month',
            'pricing_per_year'     => '/ year',
            'pricing_free'         => 'Free',
            'tier_free'            => 'Free',
            'tier_pro_monthly'     => 'Pro · monthly',
            'tier_pro_yearly'      => 'Pro · yearly',
            'tier_free_tag'        => 'For quick fixes and personal use.',
            'tier_pro_tag'         => 'For people who share links regularly.',
            'tier_free_f1'         => 'Short links, with or without an account',
            'tier_free_f2'         => 'Click stats',
            'tier_free_f3'         => 'Auto-expiring links',
            'tier_free_f4'         => '100 API calls/hour',
            'tier_pro_f1'          => 'Everything in Free',
            'tier_pro_f2'          => 'Password protection',
            'tier_pro_f3'          => 'Custom expiry (or none)',
            'tier_pro_f4'          => 'Editable links',
            'tier_pro_f6'          => '1000 API calls/hour',
            'pricing_cta_free'     => 'Create account',
            'pricing_cta_pro'      => 'Choose Pro',
            'pricing_cta_app'      => 'Go to dashboard',
            'billing_upgrade_h'    => 'Upgrade to Pro',
            'billing_upgrade_sub'  => 'Get advanced analytics, editable links, password protection, custom expiry, and more.',
            'billing_yearly_save'  => 'Save 17%',
            'billing_btn_monthly'  => 'Choose monthly',
            'billing_btn_yearly'   => 'Choose yearly',
            'billing_pro_h'        => 'You are Pro ✓',
            'billing_pro_plan'     => 'Plan',
            'billing_pro_renews'   => 'Renews',
            'billing_pro_cancels'  => 'Cancels at period end',
            'billing_pro_status'   => 'Status',
            'billing_manage'       => 'Manage subscription',
            'billing_thanks'       => 'Thanks — your upgrade is live.',
            'billing_canceled'     => 'Upgrade canceled.',
            'err_invalid_plan'     => 'Invalid plan.',
            'err_no_subscription'  => 'You don\'t have an active subscription.',
            'err_billing_unavailable' => 'Billing is unavailable right now.',
            // Pro-gated features (en)
            'err_password_pro'     => 'Password protection requires Pro.',
            'err_expiry_pro'       => 'Custom expiry requires Pro.',
            'err_upgrade_required' => 'That feature requires Pro.',
            'edit_link'            => 'Edit link',
            'edit_save'            => 'Save',
            'edit_cancel'          => 'Cancel',
            'edit_clear_password'  => 'Remove password',
            'edit_clear_expiry'    => 'Remove expiry',
            'edit_keep_password'   => 'Keep unchanged',
            'edit_new_password'    => 'New password',
            'edit_saved'           => 'Saved.',
            'utm_title'            => 'UTM builder',
            'utm_sub'              => 'Append tracking parameters to a URL.',
            'utm_field_url'        => 'Base URL',
            'utm_field_source'     => 'Source (utm_source)',
            'utm_field_medium'     => 'Medium (utm_medium)',
            'utm_field_campaign'   => 'Campaign (utm_campaign)',
            'utm_field_term'       => 'Term (utm_term, optional)',
            'utm_field_content'    => 'Content (utm_content, optional)',
            'utm_result'           => 'Tagged URL',
            'utm_copy'             => 'Copy',
            'csv_export'           => 'Export clicks (CSV)',
            'devices_title'        => 'Devices',
            // Abuse report (en)
            'title_report'         => 'Report abuse — Shortly',
            'report_title'         => 'Report a short link',
            'report_sub'           => 'Suspect phishing, malware, or illegal content? Tell us and we\'ll review.',
            'report_field_slug'    => 'Slug (the part after /)',
            'report_field_reason'  => 'Reason',
            'report_field_detail'  => 'Details (optional)',
            'report_reason_phishing' => 'Phishing',
            'report_reason_malware'  => 'Malware',
            'report_reason_illegal'  => 'Illegal content',
            'report_reason_spam'     => 'Spam',
            'report_reason_other'    => 'Other',
            'report_submit'        => 'Submit report',
            'report_thanks'        => 'Thanks — your report is logged. We\'ll review it and take the link down if it breaks the rules.',
            'report_suspended'     => 'This link has already been suspended.',
            'err_url_blocked'      => 'That domain is blocked because it\'s known for phishing or malware.',
            'err_url_blocked_threat' => 'That URL is flagged as a threat by Google Safe Browsing.',
            'err_url_ip_host'      => 'Raw IP-address hosts aren\'t allowed — use a domain name.',
            'err_url_internal_host' => 'That host looks internal (localhost / .local / .internal etc.) — use a public domain.',
            'err_target_self'      => 'You can\'t shorten a link that points back at this service.',
            'err_target_too_freq'  => 'That URL has been shortened too many times recently — try again soon.',
            'err_captcha'          => 'Verification failed. Reload the page and try again.',
            'err_link_suspended'   => 'This link has been suspended due to abuse reports.',
            // Dashboard
            'dash_title'      => 'Your links.',
            'dash_empty'      => 'No links yet.',
            'dash_empty_sub'  => 'Make your first one — <a href="%s" style="color:var(--accent);font-weight:500;">start here</a>.',
            // Unlock
            'unlock_code'     => 'Password required',
            'unlock_title'    => 'This link is locked.',
            'unlock_sub'      => 'The owner protected it with a password. Enter it to continue.',
            'btn_unlock'      => 'Unlock &amp; continue',
            // Footer
            'foot_tagline'    => 'Swedish web development with 30 years of IT background and AI as a force multiplier.',
            'foot_svc_head'   => 'Services',
            'foot_cmp_head'   => 'Company',
            'foot_con_head'   => 'Contact',
            'foot_systems'    => 'All Systems Online',
            'foot_ftax'       => 'Registered for F-tax in Sweden',
            'foot_report_link' => 'Report abuse',
            'foot_bis_member' => 'Proud member of Based In Sweden',
            // Consent banner
            'consent_text'    => 'We log each visit (IP, browser, time) for internal stats — no tracking cookies or third-party trackers. (Functional cookies for sign-in and language are used only when you actively use those features.)',
            'consent_accept'  => 'Accept',
            'consent_decline' => 'Decline',
            'consent_reset'   => 'Privacy',
            'consent_aria'    => 'Privacy notice',
            // Page titles
            'title_landing'   => 'Shortly — make a long URL shorter',
            'title_signin'    => 'Sign in — Shortly',
            'title_register'  => 'Create account — Shortly',
            'title_dashboard' => 'Dashboard — Shortly',
            'title_unlock'    => 'Password required — Shortly',
        ],
    ];
}
